Add relationships to seralizer content
zoocasa/node-data pull request #2
Opened 2020-09-21 20:18 UTC by mikaalnaik

2020-09-22 13:19 UTC, mikaalnaik commented on src/json-api/serializer.ts
> +      const content = payload.data.map(item => this.buildModel({ id: item.id, ...item.attributes, ...item.relationships }));
or do you think something more explicitly identifying the `relationship` would be better?

`{ id: item.id, ...item.attributes, relationships: item.relationships }` 
instead of
`{ id: item.id, ...item.attributes, ...item.relationships }`

2020-09-23 21:18 UTC, egjiri commented on src/json-api/serializer.ts
> +      const content = payload.data.map(item => this.buildModel({ id: item.id, ...item.attributes, ...item.relationships }));
I don't want to make this change because this is not how JSONAPI is supposed to work. Ember implements it properly so we need to emulate that functionality

2020-09-23 21:20 UTC, egjiri commented on src/json-api/serializer.ts
> +  relationships?: Record<string, unknown>
Make this more specific if possible. Something like
```js
relationships?: Record<string, {
  data: {
    id: string | number,
    type: string
  }
}>

I haven't tested this btw

2020-09-24 11:39 UTC, egjiri commented on src/json-api/serializer.ts
> +      const content = payload.data.map(item => this.buildModel({ id: item.id, ...item.attributes, ...item.relationships }));
I guess for now let's update this to not merge the contents of relationships into the main content but add it a it's own proper. See my comment on your next PR that goes with it.
```js
const content = payload.data.map(item => {
  return this.buildModel({ id: item.id, ...item.attributes, relationships: item.relationships })
});
```

2020-09-24 13:38 UTC, egjiri commented on src/json-api/serializer.ts
> +      const content = payload.data.map(item => this.buildModel({ id: item.id, ...item.attributes, ...item.relationships }));
Ignore the above comments and change this to the following.
```js
const content = payload.data.map(item => {
  return this.buildModel({ id: item.id, ...item.attributes, ...extractRelationships(item.relationships) })
});

function extractRelationships(relationshipsData) {
  // return something like { neighbourhood: { id: 12345 }}
}

2020-09-24 17:53 UTC, egjiri requested changes

2020-09-24 17:53 UTC, egjiri commented on src/json-api/serializer.ts
> +function extractRelationships(relationshipsData: Record<string, any>) {
This should be
```js
function extractRelationships(relationshipsData: jsonApiResource['relationships'] = {}) {
```

2020-09-24 17:53 UTC, egjiri commented on src/json-api/serializer.ts
> +        return this.buildModel({ id: item.id, ...item.attributes, ...extractRelationships(item.relationships!) });
Get rid of the `!` in `item.relationships!` because in this case we don't have any guarantees that we'll always have a relationship. We do in the case of a listing but we might not have it in another api.

2020-09-24 17:53 UTC, egjiri commented on src/json-api/serializer.ts
> +function extractRelationships(relationshipsData: Record<string, any>) {
If it's not too much trouble, can you add a test case for the `extractRelationships` function in the `serializer.test.ts` file. Copy the pattern of an existing test. If It's hard to figure out what to do I can walk you through how to test at 4pm after my meetings

2020-09-24 18:32 UTC, egjiri commented on src/json-api/serializer.ts
> +  if (relationshipsData) {
This looks good but I was having a bit of hard time understanding how it works so I simplified it a bit. Can you change it to this?
```js
function extractRelationships(relationshipsData: jsonApiResource['relationships'] = {}) {
  const relationships: Record<string, { id: string | number}> = {};
  Object.keys(relationshipsData).forEach(relationship => {
    relationships[relationship] = { id: relationshipsData[relationship].data.id };
  });
  return relationships;
}
```
Tests are passing so I assume it works

2020-09-24 18:33 UTC, egjiri commented on src/json-api/serializer.test.ts
> +      { id: 3, type: 'users', attributes: { 'first-name': 'Joe' }, relationships: { familyId: { data: { id: 1894, type: 'familyIds' }}}},
Let's come up with something different than `familyId` because I'm not sure if data like that comes us as camel-cased or dasherized so let's change it to a one word like `friend`, and `friends`

2020-09-24 18:37 UTC, merged